# Generated by Django 4.0.3 on 2023-06-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rangos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default='true')),
            ],
        ),
        migrations.CreateModel(
            name='Rango_productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos')),
                ('rango_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rangos.rangos')),
            ],
        ),
    ]
