# Generated by Django 4.0.3 on 2023-06-08 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rangos', '0001_initial'),
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='rango',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rangos.rangos'),
            preserve_default=False,
        ),
    ]
